<!-- ===== SIDEBAR ===== -->
<aside id="sidebar" class="sidebar">
  <div class="sidebar-header">
    <div class="logo">
      <span class="logo-icon">🎵</span>
      <span class="logo-text">SheetApp</span>
      <span id="library-count" class="library-count-badge">...</span>
    </div>
    <button id="btn-toggle-sidebar" class="icon-btn" title="Ẩn/Hiện sidebar">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 12h18M3 6h18M3 18h18"/></svg>
    </button>
  </div>

  <div class="sidebar-search">
    <div class="search-box">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="search-icon"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/></svg>
      <input id="search-input" type="text" placeholder="Tìm bài hát..." autocomplete="off">
    </div>
  </div>

  <div class="sidebar-actions">
    <button id="btn-import" class="btn btn-primary btn-sm w-full">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>
      Thêm Bài Hát
    </button>
  </div>

  <!-- QUICK JUMP -->
  <div class="quick-jump" id="quick-jump">
    <span class="quick-jump-label">Nhảy nhanh:</span>
    <div class="quick-jump-btns" id="quick-jump-btns">
      <!-- Generated by library-ui.js -->
    </div>
  </div>

  <div class="song-list-container">
    <div id="song-list" class="song-list">
      <!-- Rendered by library-ui.js -->
      <div class="empty-state">
        <span class="empty-icon">🎶</span>
        <p>Chưa có bài hát nào</p>
        <small>Nhấn "Thêm Bài Hát" để import</small>
      </div>
    </div>
  </div>
</aside>
